name: Murphy - Beach Gallery
favicon: null
layout_spectrum: 0.29031674144789577
typography_spectrum: 0.1301744095981121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2c2324'
    - '#767dbb'
    - '#d7b7b5'
    - '#fd638a'
  brandStrength: 0.3125
  lightness: 0.7811074864584953
  saturation: 0.19577814522199333
  rhythmicContrast: 0.5278289045672864
purpose: []
